{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Release.Name }}-gateway
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-route
spec:
  parentRefs:
    - name: {{ .Release.Name }}-gateway
  hostnames:
    - {{ .Values.gateway.hostname | quote }}
  rules:
    - matches:
        - path:
            type: {{ .Values.gateway.pathType }}
            value: {{ .Values.gateway.path }}
      backendRefs:
        - name: {{ .Release.Name }}-service
          port: {{ .Values.service.port }}
{{- end }} 